### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by NatalieM82** [shenkarlab/schoolLeague#23]
1) Map
2) Home page
3) Filters page
4) School info page
5) Graphs
6) Comparison page
7) Static info pages (About the projects, about the reform...)

**Comment by chenmigdal** [comment]
Searching for the right color combination

**Comment by shimritrada** [comment]
finalizing design & layout with my girl Chen :)

**Comment by shimritrada** [comment]
2) Home page- done
3) Filters page- done
4) School info page- done
5) Graphs- done
6) Comparison page-done
